kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/start.spring.io
      tags:
        - latest
        - ${DRONE_BRANCH}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push